// ----------FILTER SEARCH-------------- //
export const FILTER_STARTED = 'FILTER_STARTED'
export const FILTER_SUCCESS = 'FILTER_SUCCESS'
export const FILTER_FAILED = 'FILTER_FAILED'
export const CLEAR_FILTER = 'CLEAR_FILTER'

// ---------- GET POKEMON LIST-------------- //
export const GET_POKEMON_LIST_STARTED = 'GET_POKEMON_LIST_STARTED'
export const GET_POKEMON_LIST_SUCCESS = 'GET_POKEMON_LIST_SUCCESS'
export const GET_POKEMON_LIST_FAILED = 'GET_POKEMON_LIST_FAILED'

// ----------GET POKEMON DETAILS-------------- //
export const GET_DETAILS_STARTED = 'GET_DETAILS_STARTED'
export const GET_DETAILS_SUCCESS = 'GET_DETAILS_SUCCESS'
export const GET_DETAILS_FAILED = 'GET_DETAILS_FAILED'

// ----------GET POKEMON ENTRY-------------- //
export const GET_ENTRY_STARTED = 'GET_ENTRY_STARTED'
export const GET_ENTRY_SUCCESS = 'GET_ENTRY_SUCCESS'
export const GET_ENTRY_FAILED = 'GET_ENTRY_FAILED'
